import { Command } from 'commander';
import { join } from 'node:path';
import { access, writeFile } from 'node:fs/promises';
import { FileSessionRepository } from '@claudetree/core';
import type { Session } from '@claudetree/shared';

const CONFIG_DIR = '.claudetree';

interface ExportOptions {
  format: string;
  output?: string;
  status?: string;
}

function formatDuration(ms: number): string {
  const minutes = Math.round(ms / 60000);
  if (minutes < 60) return `${minutes}m`;
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
}

function getSessionDuration(session: Session): number {
  const start = new Date(session.createdAt).getTime();
  const end = new Date(session.updatedAt).getTime();
  return end > start ? end - start : 0;
}

function generateMarkdown(sessions: Session[]): string {
  const completed = sessions.filter((s) => s.status === 'completed').length;
  const failed = sessions.filter((s) => s.status === 'failed').length;
  const finished = completed + failed;
  const successRate = finished > 0 ? ((completed / finished) * 100).toFixed(1) : '0';

  let totalCost = 0;
  let totalInput = 0;
  let totalOutput = 0;
  let totalDuration = 0;
  let sessionsWithDuration = 0;

  for (const s of sessions) {
    if (s.usage) {
      totalCost += s.usage.totalCostUsd;
      totalInput += s.usage.inputTokens;
      totalOutput += s.usage.outputTokens;
    }
    const dur = getSessionDuration(s);
    if (dur > 0) {
      totalDuration += dur;
      sessionsWithDuration++;
    }
  }

  const avgDuration = sessionsWithDuration > 0 ? totalDuration / sessionsWithDuration : 0;

  const lines: string[] = [];
  lines.push('# claudetree Session Report');
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString().split('T')[0]}`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Sessions | ${sessions.length} |`);
  lines.push(`| Completed | ${completed} |`);
  lines.push(`| Failed | ${failed} |`);
  lines.push(`| Success Rate | ${successRate}% |`);
  lines.push(`| Total Cost | $${totalCost.toFixed(2)} |`);
  lines.push(`| Total Tokens | ${formatTokens(totalInput)} in / ${formatTokens(totalOutput)} out |`);
  lines.push(`| Avg Duration | ${formatDuration(avgDuration)} |`);
  lines.push('');

  if (sessions.length > 0) {
    lines.push('## Sessions');
    lines.push('');
    lines.push('| Issue | Status | Duration | Cost | Tokens |');
    lines.push('|-------|--------|----------|------|--------|');

    for (const s of sessions) {
      const issue = s.issueNumber ? `#${s.issueNumber}` : s.id.slice(0, 8);
      const dur = getSessionDuration(s);
      const cost = s.usage ? `$${s.usage.totalCostUsd.toFixed(4)}` : '-';
      const tokens = s.usage
        ? `${formatTokens(s.usage.inputTokens)}/${formatTokens(s.usage.outputTokens)}`
        : '-';
      lines.push(`| ${issue} | ${s.status} | ${formatDuration(dur)} | ${cost} | ${tokens} |`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [claudetree](https://github.com/wonjangcloud9/claude-tree)*');

  return lines.join('\n');
}

function formatTokens(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

export const exportCommand = new Command('export')
  .description('Generate session report (markdown or JSON)')
  .option('-f, --format <format>', 'Output format: markdown, json', 'markdown')
  .option('-o, --output <file>', 'Write to file instead of stdout')
  .option('-s, --status <status>', 'Filter by status: completed, failed, running')
  .action(async (options: ExportOptions) => {
    const cwd = process.cwd();
    const configDir = join(cwd, CONFIG_DIR);

    try {
      await access(configDir);
    } catch {
      console.error('Error: claudetree not initialized. Run "ct init" first.');
      process.exit(1);
    }

    const sessionRepo = new FileSessionRepository(configDir);
    let sessions = await sessionRepo.findAll();

    if (options.status) {
      sessions = sessions.filter((s) => s.status === options.status);
    }

    let output: string;

    if (options.format === 'json') {
      output = JSON.stringify(
        {
          generated: new Date().toISOString(),
          totalSessions: sessions.length,
          sessions: sessions.map((s) => ({
            id: s.id,
            issueNumber: s.issueNumber,
            status: s.status,
            duration: getSessionDuration(s),
            cost: s.usage?.totalCostUsd ?? 0,
            inputTokens: s.usage?.inputTokens ?? 0,
            outputTokens: s.usage?.outputTokens ?? 0,
            createdAt: s.createdAt,
            updatedAt: s.updatedAt,
          })),
        },
        null,
        2,
      );
    } else {
      output = generateMarkdown(sessions);
    }

    if (options.output) {
      await writeFile(options.output, output);
      console.log(`Report written to ${options.output}`);
    } else {
      console.log(output);
    }
  });
