import { Command } from 'commander';
import { join } from 'node:path';
import { access, readFile } from 'node:fs/promises';
import { exec as execCb } from 'node:child_process';
import { FileSessionRepository } from '@claudetree/core';
import type { Session } from '@claudetree/shared';

function execAsync(cmd: string, opts?: { cwd?: string }): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    execCb(cmd, opts ?? {}, (error, stdout, stderr) => {
      if (error) reject(error);
      else resolve({ stdout: String(stdout), stderr: String(stderr) });
    });
  });
}
const CONFIG_DIR = '.claudetree';

interface PROptions {
  session?: string;
  base: string;
  dryRun: boolean;
  all: boolean;
  token?: string;
}

interface Config {
  worktreeDir: string;
  github?: {
    token?: string;
    owner?: string;
    repo?: string;
  };
}

async function loadConfig(cwd: string): Promise<Config | null> {
  try {
    const configPath = join(cwd, CONFIG_DIR, 'config.json');
    await access(configPath);
    const content = await readFile(configPath, 'utf-8');
    return JSON.parse(content) as Config;
  } catch {
    return null;
  }
}

async function getGitDiffStat(worktreePath: string, base: string): Promise<string> {
  try {
    const { stdout } = await execAsync(
      `git diff ${base}...HEAD --stat`,
      { cwd: worktreePath },
    );
    return stdout.trim();
  } catch {
    return '(diff unavailable)';
  }
}

async function getCommitMessages(worktreePath: string, base: string): Promise<string[]> {
  try {
    const { stdout } = await execAsync(
      `git log ${base}..HEAD --pretty=format:"%s"`,
      { cwd: worktreePath },
    );
    return stdout.trim().split('\n').filter(Boolean);
  } catch {
    return [];
  }
}

async function getCurrentBranch(worktreePath: string): Promise<string> {
  const { stdout } = await execAsync(
    'git rev-parse --abbrev-ref HEAD',
    { cwd: worktreePath },
  );
  return stdout.trim();
}

function extractIssueNumber(branch: string): number | null {
  const match = branch.match(/issue-(\d+)/);
  return match ? parseInt(match[1]!, 10) : null;
}

function categorizeCommits(messages: string[]): Record<string, string[]> {
  const categories: Record<string, string[]> = {};
  for (const msg of messages) {
    const match = msg.match(/^(feat|fix|test|refactor|docs|chore|style|perf)(\(.+?\))?:\s*(.+)/);
    if (match) {
      const type = match[1]!;
      const desc = match[3]!;
      if (!categories[type]) categories[type] = [];
      categories[type]!.push(desc);
    } else {
      if (!categories['other']) categories['other'] = [];
      categories['other']!.push(msg);
    }
  }
  return categories;
}

function buildPRBody(
  session: Session,
  commits: string[],
  diffStat: string,
  issueNumber: number | null,
): string {
  const categories = categorizeCommits(commits);
  const typeLabels: Record<string, string> = {
    feat: 'Features',
    fix: 'Bug Fixes',
    test: 'Tests',
    refactor: 'Refactoring',
    docs: 'Documentation',
    chore: 'Chores',
    style: 'Style',
    perf: 'Performance',
    other: 'Other',
  };

  let body = '## Summary\n\n';

  for (const [type, items] of Object.entries(categories)) {
    const label = typeLabels[type] ?? type;
    body += `### ${label}\n`;
    for (const item of items!) {
      body += `- ${item}\n`;
    }
    body += '\n';
  }

  if (issueNumber) {
    body += `Closes #${issueNumber}\n\n`;
  }

  body += '## Session Info\n\n';
  body += `| Metric | Value |\n|--------|-------|\n`;
  body += `| Session ID | \`${session.id.slice(0, 8)}\` |\n`;
  body += `| Status | ${session.status} |\n`;

  if (session.usage) {
    body += `| Cost | $${session.usage.totalCostUsd.toFixed(4)} |\n`;
    body += `| Tokens | ${session.usage.inputTokens.toLocaleString()} in / ${session.usage.outputTokens.toLocaleString()} out |\n`;
  }

  if (session.tags?.length) {
    body += `| Tags | ${session.tags.join(', ')} |\n`;
  }

  body += '\n## Changes\n\n```\n' + diffStat + '\n```\n';
  body += '\n---\n*Generated by [claudetree](https://github.com/wonjangcloud9/claude-tree)*\n';

  return body;
}

function buildPRTitle(
  _session: Session,
  commits: string[],
  issueNumber: number | null,
): string {
  // Use first feat/fix commit as title, or first commit
  const featCommit = commits.find((c) => c.startsWith('feat:') || c.startsWith('fix:'));
  if (featCommit) {
    const prefix = issueNumber ? `#${issueNumber} ` : '';
    return `${prefix}${featCommit}`.slice(0, 70);
  }
  const prefix = issueNumber ? `Issue #${issueNumber}: ` : '';
  return `${prefix}${commits[0] ?? 'Session changes'}`.slice(0, 70);
}

async function createPRForSession(
  session: Session,
  config: Config,
  base: string,
  dryRun: boolean,
): Promise<{ url?: string; title: string; error?: string }> {
  if (!session.worktreePath) {
    return { title: '', error: 'No worktree path' };
  }

  const branch = await getCurrentBranch(session.worktreePath);
  const issueNumber = session.issueNumber ?? extractIssueNumber(branch);
  const commits = await getCommitMessages(session.worktreePath, base);

  if (commits.length === 0) {
    return { title: '', error: 'No commits to create PR from' };
  }

  const diffStat = await getGitDiffStat(session.worktreePath, base);
  const title = buildPRTitle(session, commits, issueNumber);
  const body = buildPRBody(session, commits, diffStat, issueNumber);

  if (dryRun) {
    console.log(`\n\x1b[36m--- PR Preview: ${session.id.slice(0, 8)} ---\x1b[0m`);
    console.log(`Title: ${title}`);
    console.log(`Branch: ${branch} → ${base}`);
    console.log(`Commits: ${commits.length}`);
    if (issueNumber) console.log(`Closes: #${issueNumber}`);
    console.log(`\n${body}`);
    return { title };
  }

  // Push branch first
  try {
    await execAsync(`git push -u origin ${branch}`, { cwd: session.worktreePath });
  } catch {
    // May already be pushed
  }

  // Create PR via gh CLI
  const owner = config.github?.owner;
  const repo = config.github?.repo;
  if (!owner || !repo) {
    return { title, error: 'GitHub owner/repo not configured' };
  }

  try {
    const { stdout } = await execAsync(
      `unset GITHUB_TOKEN && gh pr create --repo ${owner}/${repo} --base ${base} --head ${branch} --title "${title.replace(/"/g, '\\"')}" --body "${body.replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`,
      { cwd: session.worktreePath },
    );
    const url = stdout.trim();
    return { url, title };
  } catch (err) {
    return { title, error: err instanceof Error ? err.message : 'PR creation failed' };
  }
}

export const prCommand = new Command('pr')
  .description('Create pull requests from completed sessions')
  .option('-s, --session <id>', 'Session ID (creates PR for specific session)')
  .option('-b, --base <branch>', 'Base branch for PR (default: develop)', 'develop')
  .option('--dry-run', 'Preview PR without creating', false)
  .option('-a, --all', 'Create PRs for all completed sessions without PRs', false)
  .option('-t, --token <token>', 'GitHub token')
  .action(async (options: PROptions) => {
    const cwd = process.cwd();
    const config = await loadConfig(cwd);

    if (!config) {
      console.error('Error: claudetree not initialized. Run "claudetree init" first.');
      process.exit(1);
    }

    const sessionRepo = new FileSessionRepository(join(cwd, CONFIG_DIR));
    const sessions = await sessionRepo.findAll();

    let targets: Session[];

    if (options.session) {
      const found = sessions.find(
        (s) => s.id === options.session || s.id.startsWith(options.session!),
      );
      if (!found) {
        console.error(`Session "${options.session}" not found.`);
        process.exit(1);
      }
      targets = [found];
    } else if (options.all) {
      targets = sessions.filter((s) => s.status === 'completed');
    } else {
      targets = sessions.filter((s) => s.status === 'completed');
      if (targets.length === 0) {
        console.log('No completed sessions found.');
        process.exit(0);
      }
      console.log(`Found ${targets.length} completed session(s).`);
    }

    if (targets.length === 0) {
      console.log('No sessions to create PRs for.');
      process.exit(0);
    }

    console.log(`\n\x1b[36m╔══════════════════════════════════════════╗\x1b[0m`);
    console.log(`\x1b[36m║           Creating Pull Requests          ║\x1b[0m`);
    console.log(`\x1b[36m╚══════════════════════════════════════════╝\x1b[0m\n`);

    let created = 0;
    let failed = 0;

    for (const session of targets) {
      const issueStr = session.issueNumber ? `#${session.issueNumber}` : session.id.slice(0, 8);
      console.log(`  Processing ${issueStr}...`);

      const result = await createPRForSession(session, config, options.base, options.dryRun);

      if (result.error) {
        console.log(`  \x1b[31m✗\x1b[0m ${issueStr}: ${result.error}`);
        failed++;
      } else if (result.url) {
        console.log(`  \x1b[32m✓\x1b[0m ${issueStr}: ${result.url}`);
        created++;
      } else if (options.dryRun) {
        created++;
      }
    }

    if (!options.dryRun) {
      console.log(`\n  Created: ${created}, Failed: ${failed}`);
    }
  });
